name: Upmerge main to develop (PR)

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  upmerge:
    uses: winccoa-tools-pack/.github/.github/workflows/reusable-gitflow-upmerge.yml@main
